export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';


// companies types

export const FETCH_COMPANY_LOGOS_SUCCESS = 'FETCH_COMPANY_LOGOS_SUCCESS';
export const FETCH_COMPANY_LOGOS_REQUEST = 'FETCH_COMPANY_LOGOS_REQUEST';
export const FETCH_COMPANY_LOGOS_FAILURE = 'FETCH_COMPANY_LOGOS_FAILURE'

// top rated types
export const FETCH_TOPRATED_SUCCESS = 'FETCH_TOPRATED_SUCCESS';
export const FETCH_TOPRATED_REQUEST = 'FETCH_TOPRATED_REQUEST';
export const FETCH_TOPRATED_FAILURE = 'FETCH_TOPRATED_FAILURE';

// popular types

export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
export const FETCH_POPULAR_FAILURE = 'FETCH_POPULAR_FAILURE';
export const FETCH_POPULAR_REQUEST = 'FETCH_POPULAR_REQUEST';

// playing now types

export const FETCH_PLAYINGNOW_SUCCESS = 'FETCH_PLAYINGNOW_SUCCESS';
export const FETCH_PLAYINGNOW_FAILURE = 'FETCH_PLAYINGNOW_FAILURE';
export const FETCH_PLAYINGNOW_REQUEST = 'FETCH_PLAYINGNOW_REQUEST';

// series types

export const FETCH_SERIES_SUCCESS = 'FETCH_SERIES_SUCCESS';
export const FETCH_SERIES_FAILURE = 'FETCH_SERIES_FAILURE';
export const FETCH_SERIES_REQUEST = 'FETCH_SERIES_REQUEST';

// trending types

export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS'
export const FETCH_TRENDING_FAILURE = 'FETCH_TRENDING_FAILURE'
export const FETCH_TRENDING_REQUEST = 'FETCH_TRENDING_REQUEST'

// UPCOMING types

export const FETCH_UPCOMING_SUCCESS = 'FETCH_UPCOMING_SUCCESS'
export const FETCH_UPCOMING_FAILURE = 'FETCH_UPCOMING_FAILURE '
export const FETCH_UPCOMING_REQUEST = 'FETCH_UPCOMING_REQUEST'

// actors types

export const FETCH_ACTORS_SUCCESS= 'FETCH_ACTORS_SUCCESS'
export const FETCH_ACTORS_FAILURE = 'FETCH_ACTORS_FAILURE '
export const FETCH_ACTORS_REQUEST = 'FETCH_ACTORS_REQUEST'

// airing today types

export const FETCH_AIRINGTODAY_REQUEST = 'FETCH_AIRINGTODAY_REQUEST'
export const FETCH_AIRINGTODAY_SUCCESS = 'FETCH_AIRINGTODAY_SUCCESS'
export const FETCH_AIRINGTODAY_FAILURE = 'FETCH_AIRINGTODAY_FAILURE'







